query productSlug($slug: String!) {
  productSlug(slug: $slug) {
    id
    name
    description
    slug
    img
    price
    mrp
    stock
    time
    type
    ratings
    reviews
    vendor {
      id
      firstName
      lastName
      city
      avatar
      ratings
      reviews
      info {
        store
        public
        storePhotos
      }
    }
  }
}
