mutation updateProfile(
  $kitchenPhotos: [String]
  $public: Boolean
  $store: String
  $about: String
) {
  updateProfile(
    info: {
      kitchenPhotos: $kitchenPhotos
      public: $public
      store: $store
      about: $about
    }
  ) {
    firstName
    lastName
    avatar
    address {
      address
      town
      city
      state
      zip
    }
    info {
      public
      store
      kitchenPhotos
      about
    }
  }
}
